### PR TITLE
Quicksort method (iterative and recursive) and tests

### PR DESCRIPTION
**Pull request by maximussage1**

### CODE REVIEW

**Comment by charlieitesm** [comment]
Looks good, one thing I'm thinking is: did you ran a coverage report? I haven't, but it seems like the recursive quick_sort is no longer called, correct? If so, the coverage doesn't cover those lines, correct? @maximussage1

**Review by charlieitesm — COMMENTED** [review]
What's the coverage for this?

**Comment by maximussage1** [comment]
You are right, let me remove the unneeded algorithm.

**Review by charlieitesm — APPROVED** [review]
OSOM! Thanks René!

**Pull request merged**
